### ISSUE TITLE
Crash on exit in bash

### ISSUE THREAD

**Issue by pke** [lorenzofox3/zora-node#2]
When running `pta` ~~on Windows 8.1~~ on Windows 8.1 or my Linux system over ssh in the git bash/VSCode/terminal it runs the test just fine but on exit throws those errors:

```bash
✔ PASS: 12
⚠ SKIP: 0
✔ FAIL: 0

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STDOUT_CLOSE]: process.stdout cannot be closed
    at WriteStream.stdout._destroy (internal/process/stdio.js:24:18)
    at WriteStream.destroy (internal/streams/destroy.js:32:8)
    at WriteStream.Socket._final (net.js:353:17)
    at callFinal (_stream_writable.js:612:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! Test failed.  See above for more details.
```

**Comment by lorenzofox3** [comment]
I am not able to reproduce and it's a bit tricky where I live to download a VM. However, from the stacktrace you provided I might know [what causes the issue](https://github.com/lorenzofox3/zora-node/commit/3bdb0e2e9bf1e5449ad212536b3866cc372a50f8#diff-a348a86a2de1699475eb7c8d9fa3bbfaL43). I have pushed want I thought would solve the issue, let me know if it does not help with the newest version
